//to establish JDBC Connection
spring.datasource.url=jdbc:mysql://localhost:3306/ripae_co
spring.datasource.username=root
spring.datasource.password=Akshaya2005!

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081
